### Requisição para a raiz
GET http://localhost:5130/

### Requisição para a URL /b
GET http://localhost:5130/api/product/list

### Receber info pela URL
GET http://localhost:5130/repositorio/EduardoHenriqueR/monday
###
POST http://localhost:5130/api/product/create/feijao

### Receber info pelo corpo da requisição
POST http://localhost:5130/usuario
Content-Type: application/json

{
    "nome" : "Marlon",
    "idade" : 26
}

###
POST http://localhost:5130/product
Content-Type: application/json

{
    "id" : 1,
    "name" : "ChineseRice",
    "quantity" : 5,
    "price" : 1.99,
    "description" : "Chinese style rice."

}